"""Added Follow model

Revision ID: 1278271dbcdc
Revises: a3d5699a7167
Create Date: 2026-01-26 14:21:07.632214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1278271dbcdc"
down_revision: Union[str, Sequence[str], None] = "a3d5699a7167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("follow_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follow_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "follow_user_id", name="uq_user_follow"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follows")
    # ### end Alembic commands ###
